# Generated by Django 4.0.5 on 2022-07-01 12:27

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=blog.models.get_upload_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='default_thumb.jpg', upload_to=blog.models.get_thumb_upload_path, verbose_name='Thumbnail'),
        ),
    ]
